### PR TITLE
Detect conda env using sys.executable

### LINKED ISSUE #74: Inconsistent kernel environment uploaded in jupyter notebook
Hi, 

We use cluster-pack in jupyter notebooks with conda environments. 
An issue we've found is that when the kernel is in a different conda environment than the jupter notebook server, the uploaded zip (`env_name.tar.gz`) contains the envionrment of jupyter notebook but the description file `env_name.tar.json` list the correct kernel environment.

A concrete example:
1. `jupyter notebook` installed and launched from `jupyter` conda env
2. Another conda env `tf` is created and its kernel is installed
3. Launch a notebook using the `tf` kernel
4. Do `package_path, _ = cluster_pack.upload_env()`
5. `jupyter.tar.json` and `jupyter.tar.gz` are uploaded
6. `jupyter.tar.json` lists correctly the libs in `tf` conda env (not `jupyter`)
7. But `jupyter.tar.gz` packages actually the `jupyter` conda env

### PR DESCRIPTION
**Pull request by darkjh**
Fix #74

### CODE REVIEW

**Comment by darkjh** [comment]
Ping @fhoering

**Comment by darkjh** [comment]
Hello @fhoering @t-henri is it possible to have a review on this PR?

**Review by brhcriteo — APPROVED** [review]
Looks good to me.

**Comment by darkjh** [comment]
Thanks for the review! @brhcriteo 
There's another small fix #75 can you also look at it? Thanks again!

**Pull request merged**
